* 提問給龍塢陳老闆20131110
1.既有無線麥克風以及耳麥擴充
    * MIPRO MR-822 UHF Dual Channel Diversity Receiver
      * 主機二台
        * Freq. U808C
        * Freq. U808D
      * 每台分別有2 channels
==> 希望擴充無線手握麥克風二支。

    * 隨身耳麥四個，MIPRO UHF MT-801
      * 810.650MHz(B6) 199-013086
      * 810.650MHz(B6) 501-115318
      * 782.925MHz(A1) 159024045 A
      * 782.925MHz 599-008841
==> 沒有主機，希望找到可用的主機。

2.新採購方案之尋價項目
==> 合適輸出功率而且含有Effector+EQ之監聽喇叭，三個。
    * 理由如下
      * 供吉他、貝斯等樂器演出時各別同時調音用
      * 其他場合機動挪移使用
      * 搭配目前喇叭使用
      * 也可以提供S-1608的輸入，後傳至Mixer

* chen boss response
1： 請教您："希望擴充無線手握麥克風二支＂
是指共兩支對頻其中一部、還是共四支分頻對其中兩部？

是否先找出主機, 搞不好所有的無線麥克風都不用買了?可以省下不少錢,
或是依據這些發設器的頻率, 來訂購主機

唯, 在做本投資之前, 請先考慮設備衰退問題, 
一般來說設備約在使用5~10年間, 是發生問題最大的巔峰期
10年後麥克風系統的衰退會減損音質, 也是準備更換的周期(10~15年)到了
請確認是否採補足舊設備, 亦或更新新設備較符合使用成本效益?
這是需要 貴會研究的重點

2：關於本問題、茲綜合其功能後、您需要的是主動式專業用多用途喇叭、
而非樂器專用音箱（因為需要供其他場合機動挪移使用）
一般來說這種需求需要能直立橫向置放皆可使用的商品
其功能直立可當主場擴音喇叭、橫放亦可當監聽喇叭, 低音單體夠大是基本需求
並具備輸出至其他設備的功能、且需能滿足中高頻(電/木吉他,人聲, 長笛,高音弦樂等)、
中低頻（中低音大提琴，管風琴等)、低頻(供bass/keyboard等)的全方位需求
請考慮國際大廠中、最便宜的選擇為Behringer B912Neo, 
他有兩軌平衡/非平衡輸入, 專業用平衡加總輸出, 數位分頻器, 雙Compressor/Limiter可保護喇叭
具備專業先進的24bit數位訊號處理器, Low Cut, 兩段式EQ, 還有數位Noise Gate。請參考以下連結 :
http://www.behringer.com/EN/Products/B912NEO.aspx
但若需要具備效果器的音箱, 一般都是樂器專用音箱比較多, 
因為有效果器的需求的都是熱音商品, 這種音箱都是某種樂器專用品
若要照顧全部的需求, 卻要包含效果器, 這是很少見的,
所以一般都是購買監聽喇叭, 效果器自備, 一起搭配使用
為產業界的正常使用習慣
B912Neo可當監聽喇叭, 亦可當主場喇叭, 為雙用型版本

以上, 請參考, 感謝

龍塢樂府 陳昭元 謹敬

* My answer
1."希望擴充無線手握麥克風二支＂意思是說我有兩台主機各兩頻道，所以兩台主機共可以接四肢無線麥克風。但是目前我們只有兩隻無線麥克風，所以希望再買兩隻無線麥克風。這是因為這兩台主機頻率是8080c, 8080d，因此可以共用。

2.以年限來說，這四台耳麥隨身主機雖不到退役年齡，但是也滿舊了。但是，但是，因為一直收在專屬的盒子裡面，所以保存的很好。只需要將耳麥的部份換掉即可。所以享請問你這邊有沒有簡單的管道可以拿到二手的主機，因為大量的耳麥使用機會也不大。我也會網路找找。

3.謝謝提供寶貴的專業諮詢與經驗分享。網購的部份也需要把中國大陸的淘寶網算進去，因為現在已經可以再全家取貨了，運費好像70人民幣，當然大件另行加價。以Behringer B912Neo來說，網路標價是4350人民幣。所以這樣看來龍塢這邊提供的價位真的很有競爭力。
再次確認，所以這顆雙用型版本的喇叭，是可以讓吉他手調整高中低音之外，也有效果器可調嗎？從你提供的網頁詳規看來，有EQ H,M,L可調，但是卻沒有effector，所以需要另外再買effector嗎？還是我認知錯誤呢？

4.接上一問題， 那相對這一部份的功能，如果選購effector和EQ的成本是多少呢？謝謝

5.我如果使用effector和EQ將吉他輸出至s1608再傳送至mixer，而樂手透過耳麥廣播收聽成音來調音，這樣的架構下面，樂手之間必須互相循序等待來調音，沒有辦法同時一起來調音。另一方面，好像正式場合都是樂手都各自有自己的監聽喇叭來調音。所以我想請問的是，使用effector和EQ器是正規的作法嗎？謝謝

以上

* chen boss response
1.那您希望將新增的兩支掛在8080c？還是8080d？

2.請提供這些腰包發射器的廠牌、型號及頻率、我來試試看是否有辦法

3.由於系統商品的使用年限是長的、為求得長遠的服務後盾、因此我們一律交代理商貨
當然也就排除水貨、及電壓規格不符的商品、所以更彰顯我們的價格及價值
除了樂器用音箱外、是很少有內建吉他、電吉他、貝斯的專用效果器的、
因此Behringer B912Ne是需要另購效果器的。
若不考慮迴授問題、可參考Roland BA-330這顆內建簡易效果器的音箱
（可裝三號電池外攜使用、是所有自備電源音箱中、音質最佳的、音壓稍小但夠用
http://www.rolandtaiwan.com.tw/....../ba-330/
若不考慮外攜性及架設複雜度Cm-220可達到更好的超低音及中高頻的通透度(他的音質在本價格帶是少見的好）
http://www.rolandtaiwan.com.tw/....../cm-220/

4.略

5.傳統做法確實需要每人一顆監聽喇叭、但當大家一起調音時、其實一定會互相干擾的。
新的列陣喇叭、其使用觀念將革新外場成音及監聽的觀念、因為他可將這兩個系統的需求合併、
所以需要我們去適應這種新概念、但因為列陣成音原理導致音質平均度遠優於傳統喇叭、
因此縱使大家一起發聲、其聲部分辨度還是優於傳統主喇叭暨監聽兩系統的總合、但這是需要時間適應的。
若採監聽耳機、則因為排除環境干擾、更可清楚聽到每個聲部、
以上兩種方式、都將導致樂手技術直接獲得提昇、團隊精神亦可均一化、
最終音樂內容當然可獲得額外的改善

傳統上現場演出的效果器來源有三種、第一：直接使用效果器。第二：具效果器的音箱。第三：由混音機提供

以上、請參考、感謝您

龍塢樂府 陳昭元 謹敬
