* 卓志傑傳道
Electric Guitar Amp
1.	Roland Jazz Chorus JC90 
2.	Roland Jazz Chorus JC120
3.	Marshall MG50 CFX
4.	Fender Twin Reverb Mustang III 100
四選二

Acoustic Guitar Amp
1.	Roland AC60
2.	Roland AC30
二選一

Bass Guitar Amp
1.	Ampeg BA115
2.	SWR Working Pro 10
3.	Warwick CCL Combo Bass Amp
三選一

共2電1木1貝斯

電子鼓Yamaha DTX-532K 
Yamaha DTX-562K 
Roland TD 11K
Roland TD 15K

* 無線麥克風
http://www.bokaudio.com/bok-mic.htm
http://ledlight.mysinablog.com/index.php?op=ViewArticle&articleId=4505063
* 主控區前後位置的優點考量
** 位於前面的優點
*** 台上樂手容易操控。
*** 音控人員容易上台緊急維修。
*** 操控小廳電燈開關容易。

** 位於後面的優點
*** 聲音監控較全面。
*** 音控人員方便討論，不影響會眾及講者。
*** 地板佈線較不影響人員進出（因為典禮時候前面出入及站立頻繁）。

* wireless video
** Actiontec MyWirelessTV HDMI 
*** 一對二套件組
**** http://tw.page.bid.yahoo.com/tw/auction/f54465596;_ylt=Am6Dc3fwr5EK4eZgYVYEa.ZyFbN8;_ylv=3?u=Y0280373231
**** 一對二的,優惠您12900元含運
*** functions
● 一對多同步HDMI無線接收器 
● 安裝簡單免安裝軟體 
● 採用Wifi無線傳送HDMI訊號 
● 畫質可達1080P@60並支援3D 
● 最遠傳輸距離可達46公尺 
● 具有紅外線無線延伸功能 
● 接收端接鍵盤滑鼠可控制遠端電腦 
● NCC認證碼：CCAB09LP1380 	
*** tech spec
**** 單一機盒: 
- 尺寸(長x寬x高)：約12*11*4cm 
- 重量：約145.3g 
**** 影音規格： 
- 輸入端子：HDMI（發射端） 
- 輸出端子：HDMIx1（發射端）、HDMI（接收端） 
- 最高解析度： 1920 x 1080 @60 Full HD 
- 傳輸方式：同步輸出 
- 2D/3D效果：支援 
- 支援影像：H.264 
- 支援無壓縮音效 
**** 無線傳輸： 
- 有效範圍：150英呎(46m) 
- 頻率：2.4 GHz / 5GHz (自動切換) 
- 影像傳輸延遲：<20ms (Game mode) 
- NCC認證碼：CCAB09LP1380T3 
**** 初始化設定及配對：PIN/PBC 
**** 影像QoS：進階 
**** 頻道選擇：動態WiFi 
**** HDCP2.0：是 
**** 電力需求：5V DC 

** HDMI 轉 VGA 訊號轉接線

* 提問給龍塢陳老闆20131110
#+BEGIN_COMMENT
1.既有無線麥克風以及耳麥擴充
    * MIPRO MR-822 UHF Dual Channel Diversity Receiver
      * 主機二台
        * Freq. U808C
        * Freq. U808D
      * 每台分別有2 channels
==> 希望擴充無線手握麥克風二支。

    * 隨身耳麥四個，MIPRO UHF MT-801
      * 810.650MHz(B6) 199-013086
      * 810.650MHz(B6) 501-115318
      * 782.925MHz(A1) 159024045 A
      * 782.925MHz 599-008841
==> 沒有主機，希望找到可用的主機。

2.新採購方案之尋價項目
==> 合適輸出功率而且含有Effector+EQ之監聽喇叭，三個。
    * 理由如下
      * 供吉他、貝斯等樂器演出時各別同時調音用
      * 其他場合機動挪移使用
      * 搭配目前喇叭使用
      * 也可以提供S-1608的輸入，後傳至Mixer
#+END_COMMENT

* chen boss response
1： 請教您："希望擴充無線手握麥克風二支＂
是指共兩支對頻其中一部、還是共四支分頻對其中兩部？

是否先找出主機, 搞不好所有的無線麥克風都不用買了?可以省下不少錢,
或是依據這些發設器的頻率, 來訂購主機

唯, 在做本投資之前, 請先考慮設備衰退問題, 
一般來說設備約在使用5~10年間, 是發生問題最大的巔峰期
10年後麥克風系統的衰退會減損音質, 也是準備更換的周期(10~15年)到了
請確認是否採補足舊設備, 亦或更新新設備較符合使用成本效益?
這是需要 貴會研究的重點

2：關於本問題、茲綜合其功能後、您需要的是主動式專業用多用途喇叭、
而非樂器專用音箱（因為需要供其他場合機動挪移使用）
一般來說這種需求需要能直立橫向置放皆可使用的商品
其功能直立可當主場擴音喇叭、橫放亦可當監聽喇叭, 低音單體夠大是基本需求
並具備輸出至其他設備的功能、且需能滿足中高頻(電/木吉他,人聲, 長笛,高音弦樂等)、
中低頻（中低音大提琴，管風琴等)、低頻(供bass/keyboard等)的全方位需求
請考慮國際大廠中、最便宜的選擇為Behringer B912Neo, 
他有兩軌平衡/非平衡輸入, 專業用平衡加總輸出, 數位分頻器, 雙Compressor/Limiter可保護喇叭
具備專業先進的24bit數位訊號處理器, Low Cut, 兩段式EQ, 還有數位Noise Gate。請參考以下連結 :
http://www.behringer.com/EN/Products/B912NEO.aspx
但若需要具備效果器的音箱, 一般都是樂器專用音箱比較多, 
因為有效果器的需求的都是熱音商品, 這種音箱都是某種樂器專用品
若要照顧全部的需求, 卻要包含效果器, 這是很少見的,
所以一般都是購買監聽喇叭, 效果器自備, 一起搭配使用
為產業界的正常使用習慣
B912Neo可當監聽喇叭, 亦可當主場喇叭, 為雙用型版本

以上, 請參考, 感謝

龍塢樂府 陳昭元 謹敬

* My answer
1."希望擴充無線手握麥克風二支＂意思是說我有兩台主機各兩頻道，所以兩台主機共可以接四肢無線麥克風。但是目前我們只有兩隻無線麥克風，所以希望再買兩隻無線麥克風。這是因為這兩台主機頻率是8080c, 8080d，因此可以共用。

2.以年限來說，這四台耳麥隨身主機雖不到退役年齡，但是也滿舊了。但是，但是，因為一直收在專屬的盒子裡面，所以保存的很好。只需要將耳麥的部份換掉即可。所以享請問你這邊有沒有簡單的管道可以拿到二手的主機，因為大量的耳麥使用機會也不大。我也會網路找找。

3.謝謝提供寶貴的專業諮詢與經驗分享。網購的部份也需要把中國大陸的淘寶網算進去，因為現在已經可以再全家取貨了，運費好像70人民幣，當然大件另行加價。以Behringer B912Neo來說，網路標價是4350人民幣。所以這樣看來龍塢這邊提供的價位真的很有競爭力。
再次確認，所以這顆雙用型版本的喇叭，是可以讓吉他手調整高中低音之外，也有效果器可調嗎？從你提供的網頁詳規看來，有EQ H,M,L可調，但是卻沒有effector，所以需要另外再買effector嗎？還是我認知錯誤呢？

4.接上一問題， 那相對這一部份的功能，如果選購effector和EQ的成本是多少呢？謝謝

5.我如果使用effector和EQ將吉他輸出至s1608再傳送至mixer，而樂手透過耳麥廣播收聽成音來調音，這樣的架構下面，樂手之間必須互相循序等待來調音，沒有辦法同時一起來調音。另一方面，好像正式場合都是樂手都各自有自己的監聽喇叭來調音。所以我想請問的是，使用effector和EQ器是正規的作法嗎？謝謝

以上

* chen boss response
1.那您希望將新增的兩支掛在8080c？還是8080d？

2.請提供這些腰包發射器的廠牌、型號及頻率、我來試試看是否有辦法

3.由於系統商品的使用年限是長的、為求得長遠的服務後盾、因此我們一律交代理商貨
當然也就排除水貨、及電壓規格不符的商品、所以更彰顯我們的價格及價值
除了樂器用音箱外、是很少有內建吉他、電吉他、貝斯的專用效果器的、
因此Behringer B912Ne是需要另購效果器的。
若不考慮迴授問題、可參考Roland BA-330這顆內建簡易效果器的音箱
（可裝三號電池外攜使用、是所有自備電源音箱中、音質最佳的、音壓稍小但夠用
http://www.rolandtaiwan.com.tw/....../ba-330/
若不考慮外攜性及架設複雜度Cm-220可達到更好的超低音及中高頻的通透度(他的音質在本價格帶是少見的好）
http://www.rolandtaiwan.com.tw/....../cm-220/

4.略

5.傳統做法確實需要每人一顆監聽喇叭、但當大家一起調音時、其實一定會互相干擾的。
新的列陣喇叭、其使用觀念將革新外場成音及監聽的觀念、因為他可將這兩個系統的需求合併、
所以需要我們去適應這種新概念、但因為列陣成音原理導致音質平均度遠優於傳統喇叭、
因此縱使大家一起發聲、其聲部分辨度還是優於傳統主喇叭暨監聽兩系統的總合、但這是需要時間適應的。
若採監聽耳機、則因為排除環境干擾、更可清楚聽到每個聲部、
以上兩種方式、都將導致樂手技術直接獲得提昇、團隊精神亦可均一化、
最終音樂內容當然可獲得額外的改善

傳統上現場演出的效果器來源有三種、第一：直接使用效果器。第二：具效果器的音箱。第三：由混音機提供

以上、請參考、感謝您

龍塢樂府 陳昭元 謹敬
* My answer

陳老闆您好：
1.808D

2.
** 隨身耳麥四個，MIPRO UHF MT-801
      * 810.650MHz(B6) 199-013086
      * 810.650MHz(B6) 501-115318
      * 782.925MHz(A1) 159024045 A
      * 782.925MHz 599-008841

4.可否依您的經驗建議廠牌及型號?

5.新的列陣喇叭革新外場成音及監聽的觀念. 如此的作法目前已經有專業團體採用嗎？您有經手這樣的整合專案嗎？

6.請幫忙確認以下樂器及樂手接線系統圖，以及針對？？？的部份回覆。謝謝
** 效果器
*** 機型/規格 ???
** EQ
*** 機型/規格 ???
** 腰掛接收器
*** 機型/規格 ???
** 發射主機
*** 機型/規格 ???

** -)-)-)- 表示無線傳輸
** ======  表示樂器專用多合一傳輸線 
** 樂器及樂手接線圖

  吉他--->腰掛發射器-)-)-)-接收主機--->效果器--->EQ--->S1608===>M-200i

  樂手<---耳機<---腰掛接收器-(-(-(-發射主機<---M-200i

  鼓--------->S1608===>M-200i

  鍵盤------->S1608===>M-200i

  鋼琴-)-)-)-麥克風--->S1608===>M-200i




* chen boss response
1:已收到您的更正為808D

2:目前正向同業確認可能供應來源

4：由於效果器的個人需求、喜好的主觀度極高、建議本項應由該樂器的樂手自由指定較為妥當。
     EQ部分, 通常會附在效果器或音箱上可供調整, 
     至於更好的等化器部份, 可採購最便宜的兩軌Behringer DEQ1024(10,000/部)直接調所需要的精細精準頻段,
     或直接購買報價單上已列價格之迴授抑制器FBQ100, 直接抑制迴授, 監調整EQ(但須進入功能頁面調整)
     綜上可知,直接採購效果器或音箱的綜效邊際成本是最低的, 由混音機端調整的成本是0
     DEQ1024 : http://www.behringer.com/EN/Products/DEQ1024.aspx
     FBQ100   : http://www.behringer.com/EN/Products/FBQ100.aspx

5. 相同列陣喇叭暨中控設備, 已於新近一個月在泰山美門堂架設,若有試聽需求, 
    敝公司專業音樂人士客戶、金馬獎2004最佳配樂得主張見宇牧師、
    相信他將非常歡迎  貴會的參訪、若您有任何疑問, 您亦可向他請教該系統

    另外、相同列陣喇叭國外案例無數 :
這是列陣技術性優勢的學理論述：
https://www.youtube.com/watch?v=aRoFcrRuGWo
https://www.youtube.com/watch?v=Vazso8LYpqc
https://www.youtube.com/watch?v=FBWXVg_7424&list=PLC129BF2C5353C041
這是單用一組100人的：
Francisco Alatorre Hotel California
這是名人使用介紹 :
Charlie Farren on Bose L1 Line Array Systems - Bose L1
Uptempo play Green Door, with Bose L1 sound system.
https://www.youtube.com/watch?v=J_CRS4TEulY
這是各國各種不同場合的運用： 
Bose L1 Model 2 Demo
Jordan and Waters country medley
https://www.youtube.com/watch?v=3UFfD0Ds9ag
https://www.youtube.com/watch?v=LO8EPtmYLIo
Charlie Farren on Bose L1 Line Array Systems - Bose L1
https://m.youtube.com/watch?v=AIv_nCkLC_o
https://www.youtube.com/watch?v=_h5Zzsc-WTM
一般國外運用甚至是一人配一組：
https://www.youtube.com/watch?v=ZWMJFoOfA84
Ain't No Sunshine (Salon de la musique 2010) BOSE (Milf Men i like Funk)
Sultans
Bose L1 in action
Words Won't Fit The Mouth
https://www.youtube.com/watch?v=jhV-3zy3TGg
這是100/300/500各一組的混搭使用
3 Bose L1s: Classic, Model II, & Compact - Dick Tater & The Tots
以上, 為列陣擴聲系統的案例

6. 關於效果器暨EQ部分如第4項之回覆, 但因接法有很多種, 可放在混音機前, 
　 或混音機中, 或混音機後,皆各有其優劣點, 
    組合總數相當複雜, 這恐怕不是E-MAIL方便說明的

    樂器改為無線與採用效果器或等化器是兩件事, 基本上它只是提供無線傳輸訊號而已, 
    實際線路將依樂器後, 混音機前的配置確認後, 方能有精確的系統圖, 因此, 一切皆與預算有關

7. 關於1/4TRS非平衡式線材, 建議不要太長, 15米已可能產生干擾雜訊
    若是1/4TRS平衡線, 依線材不同, 可拉最長至100米
    所以15米線, 一般都是採用6.3mm(1/4TRS)或CANON(XLR)做成平衡線
    關於是否做成平衡或非平衡?是依據您所連接的器材來決定
    如果是吉他, BASS類樂器, 這是很少有平衡輸出的, 因此15米非平衡將會有點太長
    未知您要連接的樂器為何?一般我們都是手工製作相關客訂線材
以上, 請參考

